### ISSUE TITLE
Step 3.iii has the wrong value

### ISSUE THREAD

**Issue by gregtrob** [FusionAuth/fusionauth-example-react#2]
I was following the instructions to get this example running locally.  It states 

"Set the OAuth Redirect URI to http://localhost:9000/oauth-redirect."

I believe the line should actually be

"Set the OAuth Redirect URI to http://localhost:9000/oauth-callback" as on oauth-redirect I get an error saying it does not exist. Once I changed to oauth-calback I was able to sign in

**Comment by mooreds** [comment]
Thanks for the bug report! I fixed this in https://github.com/FusionAuth/fusionauth-example-react/commit/b1dd47752b81a8794aa705f848a54363145684fe
